name: Build ffmpeg

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NWJS_VERSION: "0.46.0"
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Clone nwjs-ffmpeg-prebuilt
      run: |
        git clone https://github.com/iteufel/nwjs-ffmpeg-prebuilt.git
        mkdir nwjs-ffmpeg-prebuilt/_output
    - name: Download dependencies
      run: |
        cd nwjs-ffmpeg-prebuilt
        npm install
    - name: Build ffmpeg
      run: |
        cd nwjs-ffmpeg-prebuilt
        sudo node build.js --arch x64 --version $NWJS_VERSION --out _output
        find .
        touch dummy.zip
        cp *.zip _output
        tar -cvf ../output.tar _output
    - name: Store zip as artifact
      uses: actions/upload-artifact@v1
      with:
        name: "output.tar"
        path: "output.tar"

